language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t kowal001/docker-react -f Dockerfile.dev .

script:
 - docker run kowal001/docker-react npm run test -- --coverage
